Add WorldGenerator, Biome and Block module
FlintMC/FlintMC pull request #100
Opened 2021-01-11 18:13 UTC by derrop

This PR adds:
- Methods to generate worlds in every world type of Minecraft (flat and buffet being the only ones with more specific configuration than just one type)
- An abstraction of biomes and blocks that were necessary for the world generators.

Closes #88

2021-01-13 17:50 UTC, zortax requested changes

2021-01-13 17:50 UTC, zortax commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/Biome.java
> +}
javadocs missing

2021-01-13 17:50 UTC, zortax commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/BiomeCategory.java
> +}
javadocs

2021-01-13 17:50 UTC, zortax commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/BiomeEntitySpawnRate.java
> +}
javadocs

2021-01-13 17:50 UTC, zortax commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/BiomeMapper.java
> +}
javadocs

2021-01-13 17:50 UTC, zortax commented on mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/biome/VersionedBiomeMapper.java
> +}
inheritDoc

2021-01-13 17:50 UTC, zortax commented on mcapi/src/v1_16_4/java/net/flintmc/mcapi/v1_16_4/resources/VersionedResourceLocationProvider.java
> +
inheritDocs

2021-01-14 08:35 UTC, Janrupf requested changes

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/generator/DefaultBuffetWorldGeneratorSettings.java
> +    Preconditions.checkNotNull(this.type, "Invalid type provided");
Please don't use google dependencies for that. As Minecraft also depends on it, this could potentially break. I'd rather see a utility method in one of the modules or just a normal null check.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/generator/DefaultExtendedWorldGeneratorSettings.java
> +      return this.seed(seed.hashCode());
Is this Minecrafts implementation? Might still be a good idea to log the exception with a warning at least, unless Minecraft does it exactly like this.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/generator/DefaultExtendedWorldGeneratorSettings.java
> +    Preconditions.checkNotNull(this.difficulty, "Invalid difficulty set");
See comment on null checks above.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/generator/DefaultWorldGeneratorBuilder.java
> +    Preconditions.checkNotNull(this.name, "No name set");
See comment on null checks above.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/generator/flat/DefaultFlatWorldGeneratorSettings.java
> +    Preconditions.checkArgument(!this.layers.isEmpty(), "No layers set");
See comment on null checks above.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/resources/ResourceLocationProvider.java
> +  ResourceLocation fromMinecraft(Object handle);
Missing documentation

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/Biome.java
> +}
Missing documentation

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/BiomeEntitySpawnRate.java
> +}
Missing documentation

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/BiomeMapper.java
> +}
Missing documentation

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/biome/BiomeRegistry.java
> +}
Missing documentation

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/WorldGeneratorBuilder.java
> +  WorldGeneratorBuilder datapackCodec(DatapackCodec codec);
It might make sense to add a `supportsDatapackCodec` method

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/WorldGeneratorBuilder.java
> +  DatapackCodec datapackCodec();
I'm not sure if this should return a non null value if the version does not support this. We need to find a framework common way of handling version specific features.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/buffet/BuffetWorldGeneratorType.java
> +   * A default world consisting one biome.
Typo: A default world consisting **of** one biome.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldGeneratorSettings.java
> +   * #getStructures()} contains the given structure.
If it is only similar, describe how it differs. If it is exactly the same, use "Equal to [...]"

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldGeneratorSettings.java
> +   * added, nothing will happen.
Should probably be: If the structure **has not been** added, nothing will happen.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldGeneratorSettings.java
> +   *
Should probably be: If the given structure **has not been added yet**, [...]

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldGeneratorSettingsSerializer.java
> +  FlatWorldGeneratorSettings deserialize(String serialized);
What happens if the deserialization fails? This should be indicated by the javadoc.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldLayer.java
> +   * @return The height of this layer in blocks, always > 0
Escape the `>`, else javadoc generation fails.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldLayer.java
> +     * @param layerHeight The height of this layer in blocks, needs to be > 0
Escape the `>`, else javadoc generation fails.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldLayer.java
> +     * @param layerHeight The height of this layer in blocks, needs to be > 0
Escape the >, else javadoc generation fails.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldStructure.java
> + * supported in every version.
There should be a check which structure is available in the current version. This check should then be linked in the javadoc here.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/StructureOption.java
> + * option is supported for every structure.
There should be a check which option is available for which structure. This check should then be linked in the javadoc here.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/type/WorldType.java
>    boolean canBeCreated();
Please explain in the javadoc why this can be potentially false.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/type/WorldTypeRegistry.java
> +   * @return The world type with the given name or {@code null} if there is no type matching the
Missing `,` before `if`

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/generator/VersionedWorldGeneratorSettingsImplementation.java
> +        throw new RuntimeException("Could not create save folder", exception);
Don't use `RuntimeException`, use either a self made unchecked exception or a matching unchecked Java built-in exception.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/generator/VersionedWorldGeneratorSettingsImplementation.java
> +    } catch (Exception var4) {
This exception should not be named `var4`, and it should also not just be thrown away.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/block/Block.java
> +   * @return The hardness of the block in the range from 0 to 5 or {@code -1} if this block is
Missing `,` before `if`

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/block/Block.java
> +   * @return The redstone power for comparators in the range from 0 to 15 or {@code 0} if this block
Missing `,` before `if`

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldGeneratorSettings.java
> +   * Retrieves the layers of this settings object. The lowest value in this array (index 0) will be
Should probably be: The **first** value in this array [...]

If you want to make clear that the array represents the layers in order, I'd suggest use "The order in the array represents the order of layers in the world from the lowest to the highest ordered by index".

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/generator/flat/FlatWorldGeneratorSettings.java
> +public interface FlatWorldGeneratorSettings {
Consider adding a `layerCount` method. There seem to be references to a non-existent `size` method, which retrieves the count of layers.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/v1_16_4/java/net/flintmc/mcapi/v1_16_4/world/generator/VersionedWorldGeneratorMapper.java
> +      "dynamicRegistries+" + UUID.randomUUID().toString();
Is there a real reason this is random? I'm not sure if this is a good idea.

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/v1_16_4/java/net/flintmc/mcapi/v1_16_4/world/generator/VersionedWorldGeneratorSettingsImplementation.java
> +    } catch (Exception var4) {
See comments in 1.15.2 implementation

2021-01-14 08:35 UTC, Janrupf commented on mcapi/src/v1_16_4/java/net/flintmc/mcapi/v1_16_4/world/generator/flat/FlatPresetsShadow.java
> +  String func_243303_b(Registry<Biome> registry, FlatGenerationSettings settings);
Maybe add a comment with the deobfuscated name of the method.

2021-01-14 08:36 UTC, derrop commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/generator/DefaultExtendedWorldGeneratorSettings.java
> +      return this.seed(seed.hashCode());
This is exactly Minecraft behavior, you can also use a string as a seed for your world.

2021-01-14 08:38 UTC, Janrupf commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/generator/DefaultExtendedWorldGeneratorSettings.java
> +      return this.seed(seed.hashCode());
Alright, lets keep it like that then

2021-01-14 19:22 UTC, Janrupf approved these changes, later dismissed

2021-01-14 19:25 UTC, Janrupf commented
https://github.com/FlintMC/FlintMC/pull/100#discussion_r556352397 - waiting for this to be resolved, everything else looks good!

2021-01-15 20:12 UTC, Janrupf approved these changes

2021-01-15 21:21 UTC, l1ving approved these changes

2021-01-18 15:11 UTC, zortax approved these changes

2021-01-18 15:12 UTC, merged