Fixes the parsing of text formatting
FlintMC/FlintMC pull request #115
Opened 2021-01-22 16:55 UTC by R0bbyYT

Closes #71

2021-01-22 17:01 UTC, derrop requested changes

2021-01-22 17:01 UTC, einrobin commented on mcapi/src/main/java/net/flintmc/mcapi/world/scoreboad/team/Team.java
> +  Optional<ChatFormat> getOptionalChatFormat();
Maybe remove the "Optional" from the name of these methods (and rename getOptionalTeamColor to getColor)?

2021-01-22 17:01 UTC, einrobin commented on mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/scoreboard/VersionedScoreboardInterceptor.java
> +  version = "1.15.2")
Apply autoformat

2021-01-22 17:01 UTC, derrop commented on mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/scoreboard/listener/VersionedPlayerTeamChangeListener.java
> +  @Override
Missing inheritDoc

2021-01-22 17:01 UTC, derrop commented on mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/scoreboard/listener/VersionedPlayerTeamChangeListener.java
> +  @Override
Missing inheritDoc

2021-01-22 17:01 UTC, derrop commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/scoreboard/score/DefaultPlayerTeam.java
> +  @Override
Missing inheritDoc

2021-01-22 17:03 UTC, juliarn commented
What we thought about too is merging the ChatColor and TextFormat enums together like it's done in Bukkit for example. Then we would not need a string there.

2021-01-22 17:21 UTC, juliarn requested changes

2021-01-22 17:21 UTC, juliarn commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/world/scoreboard/DefaultScoreboard.java
> +    System.out.println("Removing... " + username);
This should probably be removed

2021-01-23 02:50 UTC, Janrupf commented on mcapi/src/main/java/net/flintmc/mcapi/world/scoreboad/team/Team.java
> +  Optional<ChatFormat> getOptionalChatFormat();
I also wonder if `Optional<ChatFormat>` makes sense, or if it should just return null.

2021-02-01 17:42 UTC, juliarn submitted a review, later dismissed

2021-02-01 17:51 UTC, juliarn approved these changes, later dismissed

2021-02-01 17:52 UTC, derrop approved these changes, later dismissed

2021-02-01 17:58 UTC, juliarn approved these changes

2021-02-01 18:24 UTC, merged