212 create model renderer api
FlintMC/FlintMC pull request #27
Opened 2020-12-16 11:06 UTC by jan-br

Closes https://github.com/FlintMC/FlintMC/issues/26

2020-12-17 16:47 UTC, R0bbyYT commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/render/DefaultMinecraftRenderMeta.java
> +public class DefaultMinecraftRenderMeta implements MinecraftRenderMeta {
The `@Override` annotations and `{@inheritDoc}`'s are missing

2020-12-17 16:47 UTC, R0bbyYT commented on mcapi/src/main/java/net/flintmc/mcapi/entity/render/EntityModelBoxHolder.java
> +public interface EntityModelBoxHolder extends ModelBoxHolder<Entity, EntityRenderContext> {
Documentation is missing

2020-12-17 16:47 UTC, R0bbyYT commented on mcapi/src/main/java/net/flintmc/mcapi/entity/render/EntityRenderContext.java
> +public interface EntityRenderContext
Documentation is missing

2020-12-17 16:47 UTC, R0bbyYT commented on mcapi/src/main/java/net/flintmc/mcapi/render/MinecraftRenderMeta.java
> +public interface MinecraftRenderMeta {
Documentation is missing

2020-12-17 16:47 UTC, R0bbyYT commented on mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/entity/render/ModelRendererInterceptorOld.java
> +public class ModelRendererInterceptorOld {
I think this class should not be committed with?

2020-12-17 16:47 UTC, R0bbyYT commented on render/model-renderer/src/internal/java/net/flintmc/render/model/internal/DefaultModelBox.java
> +public class DefaultModelBox implements ModelBox {
The `@Override` annotations and `{@inheritDoc}`'s are missing

2020-12-17 16:47 UTC, R0bbyYT commented on render/model-renderer/src/internal/java/net/flintmc/render/model/internal/DefaultRendererRepository.java
> +public class DefaultRendererRepository implements RendererRepository {
The `@Override` annotations and `{@inheritDoc}`'s are missing

2020-12-17 16:47 UTC, R0bbyYT commented on render/model-renderer/src/main/java/net/flintmc/render/model/ModelBox.java
> +public interface ModelBox {
Documentatino is missing.

2020-12-17 16:47 UTC, R0bbyYT commented on util/math/src/main/java/net/flintmc/util/math/matrix/Matrix3x3.java
> +
Documentation is missing

2020-12-17 16:47 UTC, R0bbyYT commented on mcapi/src/main/java/net/flintmc/mcapi/render/MinecraftRenderContext.java
> +
Documentation is missing.

2021-01-14 18:24 UTC, Janrupf commented
Please re-visit some of the commits and their respective messages and rename/squash them where appropriate.

2021-01-14 18:28 UTC, Janrupf requested changes
Please re-visit some of the commits and their respective messages and rename/squash them where appropriate.

2021-02-23 10:01 UTC, jan-br commented on mcapi/src/internal/java/net/flintmc/mcapi/internal/render/DefaultMinecraftRenderMeta.java
> +public class DefaultMinecraftRenderMeta implements MinecraftRenderMeta {
renamed to VersionedMinecraftRenderMeta.

2021-02-26 13:05 UTC, jan-br commented on mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/entity/render/ModelRendererInterceptorOld.java
> +public class ModelRendererInterceptorOld {
already deleted

2021-03-01 08:12 UTC, jan-br commented
> Please re-visit some of the commits and their respective messages and rename/squash them where appropriate.

Simply cant get git squash to work there. "Commit has 2 parents"

2021-03-02 10:32 UTC, Janrupf approved these changes
Decided to squash merge

2021-03-02 10:38 UTC, merged